#!/bin/bash
# Build the membrane system: PACKMOL-Memgen bilayer + tleap assembly -> Amber prmtop/rst7.
# Produces System A (receptor + ZH853 + Gi in POPC:chol 9:1). Run on a CPU node.
#
# IMPORTANT: do NOT `module load amber` here -- a system AmberTools conflicts with the conda
# env's AMBERHOME and breaks tool discovery (packmol-memgen: "reduce not available").
#   module unload amber cuda cudnn 2>/dev/null || true
set -euo pipefail
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate zh853mor-prep   # AmberTools / PACKMOL-Memgen / obabel / reduce live here

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
HERE="$(cd "$(dirname "$0")" && pwd)"

# --- build in a PRISTINE directory --------------------------------------------------------
# packmol-memgen writes to CWD *and reuses whatever it finds there*: the component PDBs
# (POPC/CHL1/WAT/Na+/Cl-, cf. its "Using WAT.pdb in the folder" message) and the preprocessed
# protein files (receptor_Trim_H.pdb, *.grid.pdb, receptorin_EMBED*.pdb). A stale component PDB
# whose atom order no longer matches the "atoms 1 20 / atoms 88 131" head/tail constraints in the
# generated packmol.inp makes PACKMOL fail with
#   "unable to put the molecules in the desired regions even without considering distance
#    tolerances" / "Maximum violation of the restraints: ~26" (= one lipid length, 100% of copies),
# and no change of packmol-memgen flags will fix it. So: always start empty.
BUILD="${BUILD_DIR:-$HERE/build_$(date +%Y%m%d_%H%M%S)}"
mkdir -p "$BUILD"
[ -z "$(ls -A "$BUILD")" ] || { echo "ERROR: build dir $BUILD is not empty."; exit 1; }
echo "Building in $BUILD"

# --- stage inputs -------------------------------------------------------------------------
# Receptor: use the membrane-ORIENTED file (normal along z) so --preoriented is valid.
# Produced by `make prep-orient` (src/02.05.00_orient_receptor.py). PPM/OPM is preferred for
# production; swap in the PPM-oriented PDB here if you have it.
cp "$REPO/intermediate/02.05.00_oriented/receptorR_oriented.pdb" "$BUILD/receptor.pdb"
cp "$HERE/tleap.in" "$HERE/make_tleap.py" "$HERE/check_placement.py" "$BUILD/"
# Ligand parameters come from ligand_resp/run_resp.sh (run that first):
cp "$HERE"/ligand_resp/ZH853.mol2 "$HERE"/ligand_resp/ZH853.frcmod "$BUILD/" 2>/dev/null || \
  echo "WARNING: ZH853.mol2/.frcmod not found -- run ligand_resp/run_resp.sh first."

cd "$BUILD"

# --- pack the solvated bilayer around the oriented receptor ---
# POPC:CHL 9:1, 0.15 M NaCl, >=15 A water pad, extra z for the Gi domain (SPECIFICATION D-4/D-10).
# No --parametrize: packmol-memgen only builds/solvates the box; tleap.in does the FF assignment.
# NB: do NOT add --verbose -- packmol-memgen 2025.1.29 crashes on it ("NameError: streamer");
# for diagnostics inspect the generated packmol.inp / packmol-memgen.json instead.
packmol-memgen \
  --pdb receptor.pdb \
  --lipids POPC:CHL1 --ratio 9:1 \
  --salt --salt_c Na+ --saltcon 0.15 \
  --dist 15 --dist_wat 17.5 \
  --preoriented

# packmol-memgen writes bilayer_<input>.pdb; normalize the name for tleap.in.
# It exits 0 even when PACKMOL fails ("CRITICAL: No output file generated by PACKMOL"), so check.
if [ ! -s bilayer_receptor.pdb ]; then
  echo "ERROR: packmol-memgen produced no bilayer_receptor.pdb."
  echo "  Look for 'Maximum violation of the restraints' in packmol.log: a restraint-only failure"
  echo "  means the head/tail atom-index constraints in packmol.inp do not match the component PDBs,"
  echo "  not that the box is overpacked. Compare the staged POPC/CHL1/WAT PDBs against the"
  echo "  packmol_memgen library copies before touching --dist/--ratio."
  ls -1 bilayer_*.pdb 2>/dev/null
  exit 1
fi
mv -f bilayer_receptor.pdb bilayer_system.pdb

# --- verify the OPM membrane registration survived the build (SPECIFICATION D-14) ------------
# packmol-memgen re-centres the solute on its own z bounding box, which for this receptor sits
# ~5 A below the OPM midplane that 02.05.00 established. That would embed the receptor too high
# in the bilayer, silently. check_placement.py measures the offset against the lipid phosphate
# planes and fails the build rather than passing a mis-embedded system to tleap. Set
# SKIP_PLACEMENT_CHECK=1 only to inspect a known-bad build.
if [ "${SKIP_PLACEMENT_CHECK:-0}" != "1" ]; then
  python check_placement.py bilayer_system.pdb receptor.pdb
fi

# --- assemble with tleap (ff19SB + Lipid21 + OPC + GAFF2/RESP ligand) ------------------------
# make_tleap.py fills in the disulfide bond (loadpdb renumbers residues sequentially, so the
# OPRM1 numbering is gone) and the periodic box (must be PACKMOL's cell, not `setBox vdw`).
python make_tleap.py bilayer_system.pdb
tleap -f tleap_run.in

echo "Built system.prmtop / system.rst7 in $BUILD."
echo "Duplicate with D2.50 (Asp116) protonated for the parallel run."
